.TH "src/board.c" 3 "Sun Oct 16 2016" "Organ With Port2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/board.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <msp430\&.h>\fP
.br
\fC#include <pins\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdevice_init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void device_init (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Organ With Port2 from the source code\&.
